default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: containerd_rails_development

test:
  <<: *default
  database: your_database_name_test

production:
  <<: *default
  database: your_database_name_production